apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: hlu-jsjs-oc-bucket
    meta.upbound.io/example-id: s3/v1beta1/bucketnotification
  labels:
    testing.upbound.io/example-name: opencost
spec:
  forProvider:
    region: eu-west-1
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SpotDatafeedSubscription
metadata:
  labels:
    testing.upbound.io/example-name: opencost
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: opencost
    prefix: open-cost
    region: eu-west-1
