apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    testing.upbound.io/example-name: opencost
  name: jsjs-bucket-tmsmc
spec:
  forProvider:
    region: eu-west-1
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SpotDatafeedSubscription
metadata:
  labels:
    testing.upbound.io/example-name: opencost
  name: opencost-feed
spec:
  forProvider:
    bucke: jsjs-bucket-tmsmc
    prefix: open-cost
    region: eu-west-1
