apiVersion: rds.aws.upbound.io/v1beta2
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/instance
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: friday-demo-app-dbinstance
  name: friday-demo-app-08042924
spec:
  forProvider:
    allocatedStorage: 20
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 14
    backupWindow: 09:46-10:16
    dbName: friday-demo-app
    engine: postgres
    engineVersion: "16.1"
    instanceClass: db.t3.micro
    maintenanceWindow: Mon:00:00-Mon:03:00
    passwordSecretRef:
      key: password
      name: friday-demo-app-dbinstance
      namespace: friday-demo
    publiclyAccessible: true
    region: eu-west-1
    skipFinalSnapshot: true
    storageEncrypted: true
    storageType: gp2
    username: postgres
  writeConnectionSecretToRef:
    name: friday-demo-app-dbinstance-out
    namespace: friday-demo

