apiVersion: rds.aws.upbound.io/v1beta2
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/instance
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: testapp-dbinstance
  name: testapp-dbinstance-05042024
spec:
  forProvider:
    allocatedStorage: 20
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 14
    backupWindow: 09:46-10:16
    dbName: testapp
    engine: postgres
    engineVersion: "16.1"
    instanceClass: db.t3.micro
    maintenanceWindow: Mon:00:00-Mon:03:00
    passwordSecretRef:
      key: password
      name: testapp-dbinstance
      namespace: test-app
    publiclyAccessible: true
    region: eu-west-1
    skipFinalSnapshot: true
    storageEncrypted: true
    storageType: gp2
    username: adminuser
  writeConnectionSecretToRef:
    name: testapp-dbinstance-out
    namespace: test-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: jeesondk/testcode:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: testapp-dbinstance-out
              key: host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: testapp-dbinstance-out
              key: password
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: testapp-dbinstance-out
              key: username
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: testapp-dbinstance-out
              key: port
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8080
