apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    meta.upbound.io/example-id: s3/v1beta1/bucketnotification
  labels:
    testing.upbound.io/example-name: test-lambda-alias
  name: test-lambda-alias
spec:
  forProvider:
    region: eu-west-1
