apiVersion: lambda.aws.upbound.io/v1beta1
kind: Function
metadata:
  annotations:
    meta.upbound.io/example-id: lambda/v1beta1/alias
  labels:
    testing.upbound.io/example-name: test_lambda_alias
  name: test-lambda-alias
spec:
  forProvider:
    handler: index.lambda_handler
    publish: true
    region: eu-west-1
    role: arn:aws:iam::123456789012:role/role-with-inline-policy
    runtime: python3.9
    s3Bucket: test-lambda-alias
    s3Key: lambda-alias-test.zip
