apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketObject
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketobject
  labels:
    testing.upbound.io/example-name: crossplane-test-s3
  name: object
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: crossplane-test-s3
    region: eu-west-1
    key: lambda-alias-test.zip
    source: './py-app/lambda-alias-test.zip'

