apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketObject
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketobject
  labels:
    testing.upbound.io/example-name: object
  name: object
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: s3
    forProvider:
      key: lambda-alias-test.zip
