apiVersion: lambda.aws.upbound.io/v1beta1
kind: Function
metadata:
  annotations:
    meta.upbound.io/example-id: lambda/v1beta1/alias
  labels:
    testing.upbound.io/example-name: test_lambda_alias
  name: test-lambda-alias
spec:
  forProvider:
    handler: index.lambda_handler
    publish: true
    region: eu-west-1
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: test_lambda_alias
    runtime: python3.9
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: test_lambda_alias
    s3Key: lambda-alias-test.zip
