apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketObject
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketobject
  labels:
    testing.upbound.io/example-name: object
  name: object
spec:
  initProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: s3
    region: eu-west-1
    source: lambda-alias-test.zip
    key: lambda-alias-test.zip
