apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/instanceroleassociation
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: dbinstance
  name: dbinstance1
spec:
  forProvider:
    allocatedStorage: 20
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    # backupRetentionPeriod: 14
    # backupWindow: 09:46-10:16
    dbName: test
    engine: postgres
    engineVersion: "13.7"
    instanceClass: db.t3.micro
    # kmsKeyIdSelector:
    #   matchLabels:
    #     testing.upbound.io/example-name: sample-key-ira
    # maintenanceWindow: Mon:00:00-Mon:03:00
    passwordSecretRef:
      key: password
      name: example-dbinstance
      namespace: upbound-system
    publiclyAccessible: true
    region: eu-west-1
    # skipFinalSnapshot: true
    # storageEncrypted: false
    storageType: gp2
    username: adminuser
  writeConnectionSecretToRef:
    name: example-dbinstance-out
    namespace: default