apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  generateName: crossplane-bucket-
  labels:
    testing.upbound.io/example-name: test_lambda_alias
spec:
  forProvider:
    region: us-east-2
  providerConfigRef:
    name: default
