apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: jeesondk/testcode:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: testapp-dbinstance-out
              key: endpoint
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: testapp-dbinstance-out
              key: password
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: testapp-dbinstance-out
              key: username
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: testapp-dbinstance-out
              key: port
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8080
